import type { Issue, Repo, SyncStatus, User } from '@shared/types';

const people: Record<string, User> = {
  'sarah-kwan': { login: 'sarah-kwan', name: 'Sarah Kwan', avatarUrl: null },
  'm-ito': { login: 'm-ito', name: 'Mika Ito', avatarUrl: null },
  dpatel: { login: 'dpatel', name: 'Dev Patel', avatarUrl: null },
  'ravi-n': { login: 'ravi-n', name: 'Ravi Nair', avatarUrl: null },
  'lm-chen': { login: 'lm-chen', name: 'Lin Chen', avatarUrl: null },
};

export const repos: Repo[] = [
  {
    id: 1,
    owner: 'acme',
    name: 'atlas-web',
    fullName: 'acme/atlas-web',
    isPrivate: true,
    openIssueCount: 18,
    updatedAt: '2026-03-26T10:00:00Z',
    tracked: true,
  },
  {
    id: 2,
    owner: 'acme',
    name: 'design-system',
    fullName: 'acme/design-system',
    isPrivate: true,
    openIssueCount: 7,
    updatedAt: '2026-03-25T14:00:00Z',
    tracked: true,
  },
  {
    id: 3,
    owner: 'acme',
    name: 'cli-tools',
    fullName: 'acme/cli-tools',
    isPrivate: true,
    openIssueCount: 3,
    updatedAt: '2026-03-24T09:00:00Z',
    tracked: true,
  },
  {
    id: 4,
    owner: 'acme',
    name: 'docs-site',
    fullName: 'acme/docs-site',
    isPrivate: false,
    openIssueCount: 12,
    updatedAt: '2026-03-23T16:00:00Z',
    tracked: true,
  },
  {
    id: 5,
    owner: 'acme',
    name: 'edge-proxy',
    fullName: 'acme/edge-proxy',
    isPrivate: false,
    openIssueCount: 2,
    updatedAt: '2026-03-20T11:00:00Z',
    tracked: false,
  },
  {
    id: 6,
    owner: 'sarah-kwan',
    name: 'dotfiles',
    fullName: 'sarah-kwan/dotfiles',
    isPrivate: false,
    openIssueCount: 0,
    updatedAt: '2026-03-05T08:00:00Z',
    tracked: false,
  },
];

function issue(partial: Omit<Issue, 'repoFullName' | 'state' | 'createdAt' | 'htmlUrl'>): Issue {
  return {
    ...partial,
    repoFullName: 'acme/atlas-web',
    state: 'open',
    createdAt: '2026-03-21T09:00:00Z',
    htmlUrl: `https://github.com/acme/atlas-web/issues/${partial.number}`,
  };
}

const tokenRefreshLoopIssue = issue({
  id: 482,
  number: 482,
  title: 'Token refresh loop on expired session',
  body: 'Client retries the refresh endpoint indefinitely when the server returns 401 with an expired grant. The loop saturates the auth service and the user is never signed out. Reproduced on staging with a grant older than 30 days.',
  type: 'bug',
  priority: 'p1',
  labels: ['bug', 'p1'],
  assignee: people['sarah-kwan'] ?? null,
  milestone: '1.4',
  dueDate: '2026-03-28',
  updatedAt: '2026-03-26T08:12:00Z',
  subtasks: [
    { id: '482-1', title: 'Reproduce with an expired grant on staging', done: true },
    { id: '482-2', title: 'Add a retry ceiling and backoff', done: false },
    { id: '482-3', title: 'Sign the user out on terminal 401', done: false },
    { id: '482-4', title: 'Cover with a regression test', done: false },
  ],
});

const keyboardShortcutsIssue = issue({
  id: 485,
  number: 485,
  title: 'Keyboard shortcuts for column moves',
  body: 'Move a focused card between type columns without the mouse.',
  type: 'feature',
  priority: 'p3',
  labels: ['enhancement'],
  assignee: people['sarah-kwan'] ?? null,
  milestone: null,
  dueDate: null,
  updatedAt: '2026-03-23T13:20:00Z',
  subtasks: [
    { id: '485-1', title: 'Focus model for cards', done: false },
    { id: '485-2', title: 'Move left and right', done: false },
    { id: '485-3', title: 'Announce the move to screen readers', done: false },
  ],
});

const bumpLucideIssue = issue({
  id: 468,
  number: 468,
  title: 'Bump lucide to 0.474',
  body: 'Two glyph names changed upstream. Check the rail and card icons after upgrade.',
  type: 'task',
  priority: 'p3',
  labels: [],
  assignee: people['dpatel'] ?? null,
  milestone: null,
  dueDate: '2026-03-27',
  updatedAt: '2026-03-21T16:45:00Z',
  subtasks: [{ id: '468-1', title: 'Update and smoke-test the icon set', done: true }],
});

export const issues: Issue[] = [
  tokenRefreshLoopIssue,
  issue({
    id: 476,
    number: 476,
    title: 'Sidebar collapses on resize under 1280px',
    body: 'Rail overlaps the first column instead of docking. Reproduced on Chrome and Safari.',
    type: 'bug',
    priority: 'p2',
    labels: ['bug', 'p2'],
    assignee: people['m-ito'] ?? null,
    milestone: null,
    dueDate: '2026-04-02',
    updatedAt: '2026-03-25T15:40:00Z',
    subtasks: [
      { id: '476-1', title: 'Reproduce at 1279px', done: false },
      { id: '476-2', title: 'Dock the rail below the breakpoint', done: false },
    ],
  }),
  issue({
    id: 471,
    number: 471,
    title: 'CSV export drops the last row',
    body: 'Off-by-one in the stream writer. Only affects exports over 500 rows.',
    type: 'bug',
    priority: 'p3',
    labels: ['bug'],
    assignee: people['dpatel'] ?? null,
    milestone: null,
    dueDate: null,
    updatedAt: '2026-03-24T11:05:00Z',
    subtasks: [
      { id: '471-1', title: 'Add a failing test at 501 rows', done: true },
      { id: '471-2', title: 'Fix the writer bound', done: true },
    ],
  }),
  issue({
    id: 489,
    number: 489,
    title: 'Bulk assign issues from the board',
    body: 'Multi-select cards, then set assignee, milestone or priority in one action.',
    type: 'feature',
    priority: 'p2',
    labels: ['enhancement', 'p2'],
    assignee: people['ravi-n'] ?? null,
    milestone: '1.4',
    dueDate: '2026-04-05',
    updatedAt: '2026-03-26T09:30:00Z',
    subtasks: [
      { id: '489-1', title: 'Multi-select interaction', done: true },
      { id: '489-2', title: 'Bulk assignee action', done: true },
      { id: '489-3', title: 'Bulk milestone action', done: false },
      { id: '489-4', title: 'Bulk priority action', done: false },
      { id: '489-5', title: 'Undo', done: false },
    ],
  }),
  issue({
    id: 490,
    number: 490,
    title: 'Saved filter views',
    body: 'Persist a filter set per repo tab and restore it on launch.',
    type: 'feature',
    priority: 'p1',
    labels: ['enhancement', 'p1'],
    assignee: people['lm-chen'] ?? null,
    milestone: '1.4',
    dueDate: null,
    updatedAt: '2026-03-26T07:50:00Z',
    subtasks: [
      { id: '490-1', title: 'Filter serialisation format', done: true },
      { id: '490-2', title: 'Persist per repo', done: false },
      { id: '490-3', title: 'Restore on launch', done: false },
      { id: '490-4', title: 'Rename a view', done: false },
      { id: '490-5', title: 'Delete a view', done: false },
      { id: '490-6', title: 'Keyboard switch between views', done: false },
    ],
  }),
  keyboardShortcutsIssue,
  issue({
    id: 465,
    number: 465,
    title: 'Split CI job by package',
    body: 'Full suite runs on every commit. Cut the 14 minute wait for docs-only changes.',
    type: 'task',
    priority: 'p2',
    labels: ['p2'],
    assignee: people['m-ito'] ?? null,
    milestone: null,
    dueDate: '2026-03-30',
    updatedAt: '2026-03-22T10:10:00Z',
    subtasks: [
      { id: '465-1', title: 'Detect changed packages', done: true },
      { id: '465-2', title: 'Matrix by package', done: true },
      { id: '465-3', title: 'Skip docs-only runs', done: true },
      { id: '465-4', title: 'Verify total wall time', done: false },
    ],
  }),
  bumpLucideIssue,
];

export const syncStatus: SyncStatus = { kind: 'synced', at: '2026-03-26T10:28:00Z' };
